In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import numpy as np

from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

state_dict = torch.load("/content/medical_model.pt", map_location=device)

print(type(state_dict))   # should be dict

<class 'collections.OrderedDict'>

In [ ]:
def build_input(row):
    age = str(row.get('age', ''))
    gender = str(row.get('gender', ''))

    return (
        f"Age: {age}. Gender: {gender}. " +   #  structured context
        str(row.get('title', '')) + " " +
        str(row.get('keywords', '')) * 2 + " " +
        str(row.get('abstract', '')) + " " +
        str(row.get('image_captions', ''))
    )

In [ ]:
df['input_text'] = df.apply(build_input, axis=1)

In [ ]:
df = pd.read_csv("/content/final_labeled_dataset.csv")

# basic cleaning
df = df.dropna(subset=['input_text', 'system_label', 'type_label'])
df = df.reset_index(drop=True)

print("Data shape:", df.shape)
df.head()

Data shape: (61437, 4)

,case_id,input_text,system_label,type_label
0,PMC3738355_01,Littoral cell angioma mimicking hepatic tumor ...,hepatobiliary,tumor
1,PMC5015624_01,Central retinal artery occlusion following las...,cardiovascular,vascular
2,PMC6381877_01,Promising Combination Therapy with Bevacizumab...,respiratory,tumor
3,PMC5287946_01,Malignant adenohypophysis spindle cell oncocyt...,multisystemic,tumor
4,PMC9106225_01,"A novel mucocele: Myxoglobulosis [['mucocele',...",ent,trauma

In [ ]:
SYSTEM_LABELS = [
    "neurological","cardiovascular","respiratory","musculoskeletal",
    "hematological","hepatobiliary","gastrointestinal","genitourinary",
    "renal","lymphatic","immunological","dermatological",
    "ophthalmic","ent","endocrine","multisystemic", "genetic"
]

TYPE_LABELS = [
    "tumor","infection","vascular","metabolic",
    "degenerative","trauma","autoimmune"
]

In [ ]:
system_labels = sorted(df['system_strong'].unique())
type_labels = sorted(df['type_strong'].unique())

print(system_labels)
print(type_labels)

In [ ]:
le_system = LabelEncoder()
le_type = LabelEncoder()

le_system.fit(SYSTEM_LABELS)
le_type.fit(TYPE_LABELS)

print("System classes:", le_system.classes_)
print("Type classes:", le_type.classes_)

System classes: ['cardiovascular' 'dermatological' 'endocrine' 'ent' 'gastrointestinal'
 'genetic' 'genitourinary' 'hematological' 'hepatobiliary' 'immunological'
 'lymphatic' 'multisystemic' 'musculoskeletal' 'neurological' 'ophthalmic'
 'renal' 'respiratory']
Type classes: ['autoimmune' 'degenerative' 'infection' 'metabolic' 'trauma' 'tumor'
 'vascular']

In [ ]:
print("Unique system labels in data:", df['system_label'].unique())
print("Unique type labels in data:", df['type_label'].unique())

Unique system labels in data: ['hepatobiliary' 'cardiovascular' 'respiratory' 'multisystemic' 'ent'
 'neurological' 'musculoskeletal' 'immunological' 'ophthalmic' 'genetic'
 'gastrointestinal' 'dermatological' 'hematological' 'renal' 'lymphatic'
 'genitourinary' 'endocrine']
Unique type labels in data: ['tumor' 'vascular' 'trauma' 'infection' 'degenerative' 'autoimmune'
 'metabolic']

In [ ]:
class MedicalDataset(Dataset):
    def __init__(self, df, tokenizer):
        self.texts = df['input_text'].tolist()
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            padding='max_length',
            truncation=True,
            max_length=256,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze()
        }

In [ ]:
full_dataset = MedicalDataset(df, tokenizer)
full_loader = DataLoader(full_dataset, batch_size=16)

In [ ]:
class MultiTaskModel(nn.Module):
    def __init__(self, num_system, num_type):
        super().__init__()
        self.encoder = AutoModel.from_pretrained("distilbert-base-uncased")
        hidden = self.encoder.config.hidden_size

        self.system_head = nn.Linear(hidden, num_system)
        self.type_head = nn.Linear(hidden, num_type)

    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = outputs.last_hidden_state[:, 0]
        return self.system_head(cls), self.type_head(cls)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = MultiTaskModel(
    num_system=len(le_system.classes_),
    num_type=len(le_type.classes_)
).to(device)

model.load_state_dict(torch.load("medical_model.pt", map_location=device))
model.eval()

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_transform.bias    | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

MultiTaskModel(
  (encoder): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (system_head): Linear(in_features=768, out_features=17, bias=True)
  (type_head): Linear(in_features=768, out_features=7, bias=True)
)

In [ ]:
sys_preds, type_preds = [], []
sys_confs, type_confs = [], []

with torch.no_grad():
    for batch in tqdm(full_loader):

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)

        sys_logits, type_logits = model(input_ids, attention_mask)

        sys_probs = F.softmax(sys_logits, dim=1)
        type_probs = F.softmax(type_logits, dim=1)

        sys_pred = torch.argmax(sys_probs, dim=1).cpu().numpy()
        type_pred = torch.argmax(type_probs, dim=1).cpu().numpy()

        sys_conf = torch.max(sys_probs, dim=1).values.cpu().numpy()
        type_conf = torch.max(type_probs, dim=1).values.cpu().numpy()

        sys_preds.extend(sys_pred)
        type_preds.extend(type_pred)

        sys_confs.extend(sys_conf)
        type_confs.extend(type_conf)

100%|██████████| 3840/3840 [08:49<00:00,  7.25it/s]

In [ ]:
df['system_pred'] = le_system.inverse_transform(sys_preds)
df['type_pred'] = le_type.inverse_transform(type_preds)

df['system_conf'] = sys_confs
df['type_conf'] = type_confs

In [ ]:
system_changes = (df['system_label'] != df['system_pred']).sum()
type_changes = (df['type_label'] != df['type_pred']).sum()

total = len(df)

print("Total samples:", total)
print("System changes:", system_changes)
print("Type changes:", type_changes)

print("System change %:", system_changes / total * 100)
print("Type change %:", type_changes / total * 100)

Total samples: 61437
System changes: 6869
Type changes: 4744
System change %: 11.180558946563146
Type change %: 7.721731204323127

In [ ]:
df_diff = df[
    (df['system_label'] != df['system_pred']) |
    (df['type_label'] != df['type_pred'])
]

for _, row in df_diff.sample(10).iterrows():
    print("="*100)
    print("TEXT:", row['input_text'][:300])
    print("OLD SYSTEM:", row['system_label'], "→ NEW:", row['system_pred'])
    print("OLD TYPE:", row['type_label'], "→ NEW:", row['type_pred'])

====================================================================================================
TEXT: Case report: Equine metacarpophalangeal joint partial and full thickness defects treated with allogenic equine synovial membrane mesenchymal stem/stromal cell combined with umbilical cord mesenchymal stem/stromal cell conditioned medium [['case report', 'cell-based medicinal product', 'equine', 'ost
OLD SYSTEM: multisystemic → NEW: musculoskeletal
OLD TYPE: tumor → NEW: tumor
====================================================================================================
TEXT: Epiphrenic Diverticulum in an Infant with Congenital Esophageal Stenosis Associated with Esophageal Atresia [['esophageal atresia', 'children', 'congenital esophageal stenosis', 'epiphrenic diverticula', 'esophageal diverticula']][['esophageal atresia', 'children', 'congenital esophageal stenosis',
OLD SYSTEM: multisystemic → NEW: gastrointestinal
OLD TYPE: degenerative → NEW: degenerative
====================================================================================================
TEXT: Severe G6PD deficiency leads to recurrent infections and defects in ROS production: Case report and literature review [['g6pd gene', 'nf-κb pathway', 'ros', 'chromosome inactivation', 'infection']][['g6pd gene', 'nf-κb pathway', 'ros', 'chromosome inactivation', 'infection']] Purpose: Severe glucose
OLD SYSTEM: hematological → NEW: hematological
OLD TYPE: tumor → NEW: infection
====================================================================================================
TEXT: Hyperammonemia in a carbamoyl-phosphate synthetase 1 deficiency recipient after living-donor liver transplantation from a carrier donor: a case report [['carbamoyl-phosphate synthetase 1 deficiency disease', 'heterozygous', 'hyperammonemia', 'liver transplantation', 'ornithine transcarbamylase defic
OLD SYSTEM: hepatobiliary → NEW: hepatobiliary
OLD TYPE: infection → NEW: metabolic
====================================================================================================
TEXT: Gastrointestinal Stromal Tumor Recurrence Presenting as a Small Bowel Obstruction: A Case Report [['abdominal mass', 'gastrointestinal stromal tumor', 'gist', 'small bowel obstruction', 'tki', 'tyrosine kinase inhibitor']][['abdominal mass', 'gastrointestinal stromal tumor', 'gist', 'small bowel obs
OLD SYSTEM: hepatobiliary → NEW: ent
OLD TYPE: tumor → NEW: tumor
====================================================================================================
TEXT: Right Ventricular Free Wall Rupture Due to Displaced Automatic Implantable Cardioverter Defibrillator (AICD) Lead [['aicd', 'cardiac device implantation', 'displaced lead', 'free wall rupture', 'right ventricle']][['aicd', 'cardiac device implantation', 'displaced lead', 'free wall rupture', 'right
OLD SYSTEM: cardiovascular → NEW: cardiovascular
OLD TYPE: trauma → NEW: vascular
====================================================================================================
TEXT: Merkel cell carcinoma presenting as malignant ascites: A case report and review of literature [['ascitic fluid', 'merkel cell carcinoma', 'metastasis']][['ascitic fluid', 'merkel cell carcinoma', 'metastasis']] The most common site of metastasis to ascitic fluid in females is from a mullerian (ovari
OLD SYSTEM: hepatobiliary → NEW: gastrointestinal
OLD TYPE: tumor → NEW: tumor
====================================================================================================
TEXT: The surprise pathology-Primary squamous cell carcinoma of the colon-A case report [['case report', 'colon', 'primary', 'squamous cell carcinoma']][['case report', 'colon', 'primary', 'squamous cell carcinoma']] Introduction: Primary squamous cell carcinomas are rare in the colon. Identified as colon
OLD SYSTEM: multisystemic → NEW: gastrointestinal
OLD TYPE: tumor → NEW: tumor
====================================================================================================
TEXT: Severe congenital neutropenia caused by the ELANE gene mutation in a Vietnamese boy with misdiagnosis of tuberculosis and autoimmune neutropenia: a case report [['autoimmune neutropenia', 'congenital severe neutropenia', 'elane', 'severe bacterial infection']][['autoimmune neutropenia', 'congenital
OLD SYSTEM: lymphatic → NEW: immunological
OLD TYPE: infection → NEW: infection
====================================================================================================
TEXT: A novel case of resolved postherpetic neuralgia with subsequent development of trigeminal neuralgia: a case report and review of the literature nannan A 72-year-old female patient is presented, who was diagnosed with herpes zoster along the left ophthalmic branch of the trigeminal nerve with associa
OLD SYSTEM: dermatological → NEW: dermatological
OLD TYPE: degenerative → NEW: infection

In [ ]:
mask_sys = (df['system_pred'] != df['system_label']) & (df['system_conf'] > 0.85)
mask_type = (df['type_pred'] != df['type_label']) & (df['type_conf'] > 0.80)

print("High-confidence system fixes:", mask_sys.sum())
print("High-confidence type fixes:", mask_type.sum())

High-confidence system fixes: 4320
High-confidence type fixes: 1972

In [ ]:
df['system_strong'] = df['system_label']
df['type_strong'] = df['type_label']

df.loc[mask_sys, 'system_strong'] = df.loc[mask_sys, 'system_pred']
df.loc[mask_type, 'type_strong'] = df.loc[mask_type, 'type_pred']

In [ ]:
df.to_csv("/content/strong_labeled_dataset.csv", index=False)

In [ ]:
import random

def inspect_random_samples(df, n=10):
    samples = df.sample(n)

    for i, row in samples.iterrows():
        print("="*100)
        print("TEXT:\n", row['input_text'][:500])

        print("\n--- LABELS ---")
        print("OLD SYSTEM :", row['system_label'])
        print("PRED SYSTEM:", row['system_pred'], "| CONF:", round(row['system_conf'], 3))
        print("FINAL SYSTEM:", row['system_strong'])

        print("\nOLD TYPE :", row['type_label'])
        print("PRED TYPE:", row['type_pred'], "| CONF:", round(row['type_conf'], 3))
        print("FINAL TYPE:", row['type_strong'])

In [ ]:
inspect_random_samples(df, n=50)

====================================================================================================
TEXT:
 Bilateral Vertebral Artery Dissection: A Case Report with Literature Review nannan Vertebral artery dissection (VAD) is a rare cause of ischemic stroke in young patients. The largely nonspecific symptoms and delayed presentation pose a serious diagnostic challenge. Medical management with either anticoagulation or antiplatelet therapy is recommended, but there are no reports of successful dual therapy. We report a case of spontaneous bilateral vertebral artery dissections (VADs) treated with bot

--- LABELS ---
OLD SYSTEM : neurological
PRED SYSTEM: neurological | CONF: 0.999
FINAL SYSTEM: neurological

OLD TYPE : vascular
PRED TYPE: vascular | CONF: 0.994
FINAL TYPE: vascular
====================================================================================================
TEXT:
 TKI-induced pure red cell aplasia: first case report of pure red cell aplasia with both imatinib and nilotinib [['chronic myeloid leukemia', 'gastrointestinal stromal tumors', 'imatinib', 'pure red cell aplasia', 'tyrosine kinase inhibitors']][['chronic myeloid leukemia', 'gastrointestinal stromal tumors', 'imatinib', 'pure red cell aplasia', 'tyrosine kinase inhibitors']] Tyrosine-kinase inhibitors (TKIs) represent the only hopes for long-term survival for patients with chronic myeloid leukaemi

--- LABELS ---
OLD SYSTEM : hematological
PRED SYSTEM: hematological | CONF: 0.519
FINAL SYSTEM: hematological

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.979
FINAL TYPE: tumor
====================================================================================================
TEXT:
 Cutaneous metastasis of choriocarcinoma: a case report nannan Choriocarcinoma is one of the malignant tumors of trophoblastic cells characterized by the secretion of human chorionic gonadotrophin (hCG) (1-3). Cutaneous metastasis is a rare presentation of choriocarcinoma but a poor prognostic sign because it is associated only with widespread disease (3-5). A 52-yr-old female complaining of dyspnea for 2 months, presented with fingertip sized erythematous nodules on the left side of the neck and

--- LABELS ---
OLD SYSTEM : dermatological
PRED SYSTEM: dermatological | CONF: 0.997
FINAL SYSTEM: dermatological

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.999
FINAL TYPE: tumor
====================================================================================================
TEXT:
 Correction of Peri-Implant Soft Tissue Fenestration With Bony Dehiscence Associated With Intrabony Defect: A 2-Year Case Report [['bony dehiscence', 'connective tissue graft', 'peri-implant soft tissue fenestration', 'peri-implantitis']][['bony dehiscence', 'connective tissue graft', 'peri-implant soft tissue fenestration', 'peri-implantitis']] Soft and hard tissue deficiencies around dental implants which can potentially compromise implant survival are commonly encountered. Complicated interven

--- LABELS ---
OLD SYSTEM : ent
PRED SYSTEM: ent | CONF: 0.997
FINAL SYSTEM: ent

OLD TYPE : degenerative
PRED TYPE: vascular | CONF: 0.419
FINAL TYPE: degenerative
====================================================================================================
TEXT:
 Profound hypoglycemia with ecstasy intoxication nannan Background. 3,4-Methylenedioxymethamphetamine (MDMA) or ecstasy is a synthetic drug that is commonly abused for its stimulant and euphoric effects. Adverse MDMA effects include hyperthermia, psychomotor agitation, hemodynamic compromise, renal failure, hyponatremia, and coma. However, endogenous hyperinsulinemia with severe persistent hypoglycemia has not been reported with MDMA use. Case Report. We report the case of a 29-year-old woman who

--- LABELS ---
OLD SYSTEM : renal
PRED SYSTEM: renal | CONF: 0.991
FINAL SYSTEM: renal

OLD TYPE : metabolic
PRED TYPE: metabolic | CONF: 0.994
FINAL TYPE: metabolic
====================================================================================================
TEXT:
 Extranodal Rosai-Dorfman Disease Presenting as a Mediastinal Mass with Pulmonary Artery Invasion nannan Rosai-Dorfman disease (RDD) is a rare, nonmalignant disorder of histiocyte proliferation typically involving the cervical lymph nodes. However, a subset of patients with RDD will display extranodal manifestations that are highly variable in presentation, more challenging to diagnose, and less likely to spontaneously regress compared to nodal disease. While case reports of extranodal involvemen

--- LABELS ---
OLD SYSTEM : cardiovascular
PRED SYSTEM: cardiovascular | CONF: 0.999
FINAL SYSTEM: cardiovascular

OLD TYPE : vascular
PRED TYPE: vascular | CONF: 0.995
FINAL TYPE: vascular
====================================================================================================
TEXT:
 Case report: Successful multimodal assessment and management of chemothorax [['port-a-cath', 'chemotherapy', 'chemothorax', 'dislocation', 'multidisciplinary management', 'pleural effusion', 'thoracoscopy', 'video-assisted thoracic surgery']][['port-a-cath', 'chemotherapy', 'chemothorax', 'dislocation', 'multidisciplinary management', 'pleural effusion', 'thoracoscopy', 'video-assisted thoracic surgery']] Dislocation or wrong placement of central venous catheters into the pleural cavity is rare,

--- LABELS ---
OLD SYSTEM : ent
PRED SYSTEM: ent | CONF: 0.989
FINAL SYSTEM: ent

OLD TYPE : tumor
PRED TYPE: infection | CONF: 0.999
FINAL TYPE: infection
====================================================================================================
TEXT:
 A 12-year-old Child with Trichinellosis, Pyomyositis and Secondary Osteomyelitis [['osteomyelitis', 'pyomyositis', 'trichinella spiralis', 'trichinellosis']][['osteomyelitis', 'pyomyositis', 'trichinella spiralis', 'trichinellosis']] Trichinellosis is a parasitic infestation affecting the skeletal muscles. Cases of trichinellosis in humans have been reported from most regions of the world. However, a review of literature revealed only two reported cases of human trichinellosis in India. Further,

--- LABELS ---
OLD SYSTEM : musculoskeletal
PRED SYSTEM: musculoskeletal | CONF: 0.983
FINAL SYSTEM: musculoskeletal

OLD TYPE : infection
PRED TYPE: infection | CONF: 0.996
FINAL TYPE: infection
====================================================================================================
TEXT:
 A Tale of Two Pathologies: MIS-C in a Patient with Pediatric Systemic Lupus Erythematosus [['covid-19', 'mis-c', 'sle', 'nephrology', 'pediatric']][['covid-19', 'mis-c', 'sle', 'nephrology', 'pediatric']] An HIV-negative 9-year-old female was admitted to the pediatric ward at a tertiary hospital in Johannesburg, South Africa for investigation of a suspected rheumatic disorder complicated by proteinuria. She was subsequently diagnosed with pediatric systemic lupus erythematosus complicated by cla

--- LABELS ---
OLD SYSTEM : renal
PRED SYSTEM: renal | CONF: 0.997
FINAL SYSTEM: renal

OLD TYPE : infection
PRED TYPE: infection | CONF: 0.998
FINAL TYPE: infection
====================================================================================================
TEXT:
 Idiopathic Intracranial Hypertension: A Case Study of Patient Engagement in the Treatment of a Chronic Disease [['challenges', 'clinician–patient relationship', 'communication', 'medical decision making', 'patient engagement', 'patient expectations', 'patient perspectives/narratives', 'patient/relationship-centered skills']][['challenges', 'clinician–patient relationship', 'communication', 'medical decision making', 'patient engagement', 'patient expectations', 'patient perspectives/narratives',

--- LABELS ---
OLD SYSTEM : neurological
PRED SYSTEM: neurological | CONF: 0.998
FINAL SYSTEM: neurological

OLD TYPE : vascular
PRED TYPE: vascular | CONF: 0.997
FINAL TYPE: vascular
====================================================================================================
TEXT:
 Case report on intravenous octreotide for the treatment of intraoperative vasoplegia following thymoma resection [['octreotide', 'non-adrenergic vasopressors', 'refractory hypotension', 'shock', 'thymoma', 'vasoplegia']][['octreotide', 'non-adrenergic vasopressors', 'refractory hypotension', 'shock', 'thymoma', 'vasoplegia']] Octreotide is a somatostatin analog known for its role in the treatment of acute variceal bleeding, enterocutaneous fistula and carcinoid syndrome. The reduction of portal

--- LABELS ---
OLD SYSTEM : cardiovascular
PRED SYSTEM: dermatological | CONF: 0.964
FINAL SYSTEM: dermatological

OLD TYPE : vascular
PRED TYPE: vascular | CONF: 0.915
FINAL TYPE: vascular
====================================================================================================
TEXT:
 A Fetus with Imperforate Anus Developing Pulmonary Hypoplasia Triggered by Transient Urethral Obstruction nannan Pulmonary hypoplasia is a rare entity in a fetus with imperforate anus. The fetus was diagnosed with high-type imperforate anus with rectourethral fistula based on the dilated fetal bowel and the presence of bowel calcification at 19 weeks of gestation. As gestation advanced, fetal ultrasonography demonstrated development of pulmonary hypoplasia, progressive bowel dilation, and persis

--- LABELS ---
OLD SYSTEM : respiratory
PRED SYSTEM: respiratory | CONF: 0.782
FINAL SYSTEM: respiratory

OLD TYPE : vascular
PRED TYPE: vascular | CONF: 0.989
FINAL TYPE: vascular
====================================================================================================
TEXT:
 Splay Toe after Freiberg-Köhler's Osteonecrosis: A Case Report of a Successful Operative Treatment in a Rare Multiplanar Foot Deformity nannan "Splay toe" is a rare deformity of the forefoot and often causes the occurrence of metatarsalgia and dysfunction while walking or weight bearing. Since it involves a deviation in the sagittal and transversal planes, often combined with a malrotation, surgical correction can be challenging. We describe a case of splay toe deformity in the forefoot causing

--- LABELS ---
OLD SYSTEM : musculoskeletal
PRED SYSTEM: musculoskeletal | CONF: 0.989
FINAL SYSTEM: musculoskeletal

OLD TYPE : degenerative
PRED TYPE: degenerative | CONF: 0.96
FINAL TYPE: degenerative
====================================================================================================
TEXT:
 A Mislocated Intrauterine Device Migrating to the Urinary Bladder: An Uncommon Complication Leading to Stone Formation nannan Intrauterine devices are a popular form of reversible contraception among women. Its administration can lead to some uncommon but serious complications such as perforation leading to its migration into adjacent organs. Like any foreign body, the presence of an IUD in the bladder can result in stone formation due to its lithogenic potential. We report a case of an IUD migr

--- LABELS ---
OLD SYSTEM : genitourinary
PRED SYSTEM: genitourinary | CONF: 0.996
FINAL SYSTEM: genitourinary

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.525
FINAL TYPE: tumor
====================================================================================================
TEXT:
 Long-term survival in a patient with unresectable liver metastases from uveal melanoma treated with transarterial chemoembolization with irinotecan eluting beads - case report and review of literature [['endovascular procedures', 'eye neoplasms/pathology', 'liver neoplasms', 'melanoma', 'therapeutic chemoembolization']][['endovascular procedures', 'eye neoplasms/pathology', 'liver neoplasms', 'melanoma', 'therapeutic chemoembolization']] Introduction: Treatment of unresectable liver metastases (

--- LABELS ---
OLD SYSTEM : hepatobiliary
PRED SYSTEM: hepatobiliary | CONF: 0.999
FINAL SYSTEM: hepatobiliary

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.998
FINAL TYPE: tumor
====================================================================================================
TEXT:
 Infection of keratocystic odontogenic tumour by pseudomonas aeruginosa nannan nan

--- LABELS ---
OLD SYSTEM : dermatological
PRED SYSTEM: dermatological | CONF: 0.956
FINAL SYSTEM: dermatological

OLD TYPE : infection
PRED TYPE: infection | CONF: 0.958
FINAL TYPE: infection
====================================================================================================
TEXT:
 Prostatic utricle cyst: a clinical dilemma [['prostatic utricle', 'stricture', 'urethra']][['prostatic utricle', 'stricture', 'urethra']] Prostatic utricle cyst is a rare midline cystic lesion between the urinary bladder and the rectum, commonly associated with hypospadias. Along with its rarity, it presents a challenge in its diagnosis and proper management. We report a case of large prostatic utricle cyst that was managed conservatively.

--- LABELS ---
OLD SYSTEM : genitourinary
PRED SYSTEM: genitourinary | CONF: 0.995
FINAL SYSTEM: genitourinary

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.949
FINAL TYPE: tumor
====================================================================================================
TEXT:
 HRT in Women Undergoing Pelvic Clearance for Endometriosis-A Case Report and a National Survey [['hrt', 'chronic pelvic pain', 'endometriosis', 'hysterectomy', 'menopause']][['hrt', 'chronic pelvic pain', 'endometriosis', 'hysterectomy', 'menopause']] The optimal hormone replacement therapy (HRT) in women who have undergone pelvic clearance for endometriosis remains uncertain with insufficient evidence. The purpose of this case report and the national survey was to highlight the potential HRT-re

--- LABELS ---
OLD SYSTEM : renal
PRED SYSTEM: renal | CONF: 0.995
FINAL SYSTEM: renal

OLD TYPE : degenerative
PRED TYPE: degenerative | CONF: 0.986
FINAL TYPE: degenerative
====================================================================================================
TEXT:
 Case report: Novel transtemporal transverse sinus decompression surgery to alleviate transverse sinus stenosis in a pulsatile tinnitus patient with restricted bilateral venous outflow [['extraluminal surgery', 'idiopathic intracranial hypertension (iih)', 'increased intracranial pressure (icp)', 'pulsatile tinnitus', 'sinus decompression', 'transverse sinus stenosis (tss)']][['extraluminal surgery', 'idiopathic intracranial hypertension (iih)', 'increased intracranial pressure (icp)', 'pulsatile

--- LABELS ---
OLD SYSTEM : ent
PRED SYSTEM: ent | CONF: 0.989
FINAL SYSTEM: ent

OLD TYPE : autoimmune
PRED TYPE: autoimmune | CONF: 0.382
FINAL TYPE: autoimmune
====================================================================================================
TEXT:
 Ladd's band in the adult, an unusual case of occlusion: Case report and review of the literature [['bowel obstruction', 'gut malrotation', 'ladd’s band']][['bowel obstruction', 'gut malrotation', 'ladd’s band']] Introduction: Malrotation of gut is a congenital anomaly of foetal intestinal rotation and it is mostly discovered in early childhood as acute intestinal obstruction. This condition is very rare and often silent in adults. Presentation of case: We present a case of 44-year-old woman admi

--- LABELS ---
OLD SYSTEM : gastrointestinal
PRED SYSTEM: gastrointestinal | CONF: 0.992
FINAL SYSTEM: gastrointestinal

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.67
FINAL TYPE: tumor
====================================================================================================
TEXT:
 Using the Flexor Reflex in a Chronic Stroke Patient for Gait Improvement: A Case Report [['flexor reflex', 'gait', 'kinematic analysis', 'stroke', 'training']][['flexor reflex', 'gait', 'kinematic analysis', 'stroke', 'training']] The flexor reflex or withdrawal reflex can be elicited by electrical stimulation of the sole of the foot, which serves as a reflex to protect the stimulated limb against tissue damage and consists of flexion movements in the hip, knee, and ankle joint. Triggering this

--- LABELS ---
OLD SYSTEM : neurological
PRED SYSTEM: neurological | CONF: 0.915
FINAL SYSTEM: neurological

OLD TYPE : vascular
PRED TYPE: vascular | CONF: 0.998
FINAL TYPE: vascular
====================================================================================================
TEXT:
 A Rare Complication following Thyroid Percutaneous Ethanol Injection: Plummer Adenoma nannan Percutaneous ethanol injection (PEI) is a technique used only for benign thyroid nodules, cystic or mixed cystic-solid with a large fluid component. It is a quite low-cost, safe, and outpatient method of treatment. Rare and severe complications have been described after PEI: jugular vein thrombosis and severe ethanol toxic necrosis of the larynx combined with necrotic dermatitis. Moreover, only four thyr

--- LABELS ---
OLD SYSTEM : dermatological
PRED SYSTEM: dermatological | CONF: 0.998
FINAL SYSTEM: dermatological

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.997
FINAL TYPE: tumor
====================================================================================================
TEXT:
 A Rare Entity of Undifferentiated Pleomorphic Sarcoma of the Mandible - A Case Report [['fibrous histiocytoma', 'histiocytes', 'multinucleated giant cells', 'pleomorphic sarcoma']][['fibrous histiocytoma', 'histiocytes', 'multinucleated giant cells', 'pleomorphic sarcoma']] The rationale: Undifferentiated pleomorphic sarcoma originally known as malignant fibrous histiocytoma was declassified by the World Health Organization in 2002 as a formal diagnostic entity and renamed as an undifferentiated

--- LABELS ---
OLD SYSTEM : dermatological
PRED SYSTEM: musculoskeletal | CONF: 0.992
FINAL SYSTEM: musculoskeletal

OLD TYPE : tumor
PRED TYPE: tumor | CONF: 0.998
FINAL TYPE: tumor
====================================================================================================
TEXT:
 Decannulation protocol in pediatric patients: case series study nannan Objective: The aim of this study was to describe the phases of a decannulation protocol and the results from its application in hospitalized children. Methods: This is a retrospective, observational study. Data were collected from medical records of decannulated patients followed up in a pediatric hospital in Belo Horizonte, Minas Gerais between 2011 and 2021. Results: Among the children followed up in the service (n=526), 23

--- LABELS ---
OLD SYSTEM : respiratory
PRED SYSTEM: respiratory | CONF: 0.929
FINAL SYSTEM: respiratory

OLD TYPE : degenerative
PRED TYPE: degenerative | CONF: 0.938
FINAL TYPE: degenerative
====================================================================================================
TEXT:
 To treat or not to treat tuberculosis -clinical decision making in patients with previous pulmonary tuberculosis using 18F-FDG PET/CT [['18f-fdg pet/ct', 'false-positive', 'tuberculosis', 'recurrent']][['18f-fdg pet/ct', 'false-positive', 'tuberculosis', 'recurrent']] Post-tuberculosis (TB) radiological changes and symptoms can mimic TB. PCR-based diagnostic tests can show positive results, suggesting the presence of Mycobacterium tuberculosis DNA in the absence of viable bacteria. We present a

--- LABELS ---
OLD SYSTEM : respiratory
PRED SYSTEM: respiratory | CONF: 0.999
FINAL SYSTEM: respiratory

OLD TYPE : infection
PRED TYPE: infection | CONF: 0.998
FINAL TYPE: infection
====================================================================================================
TEXT:
 Unmasking of Brugada syndrome by lamotrigine in a patient with pre-existing epilepsy: A case report with review of the literature [['brugada syndrome', 'epilepsy', 'ion channels', 'lamotrigine', 'sudden cardiac death (scd)', 'sudden unexpected death in epilepsy (sudep)', 'syncope']][['brugada syndrome', 'epilepsy', 'ion channels', 'lamotrigine', 'sudden cardiac death (scd)', 'sudden unexpected death in epilepsy (sudep)', 'syncope']] Brugada syndrome is an inherited cardiac channelopathy arising

--- LABELS ---
OLD SYSTEM : neurological
PRED SYSTEM: neurological | CONF: 0.999

In [ ]:
df = pd.read_csv("/content/strong_labeled_dataset.csv")



print("Data shape:", df.shape)
df.head()

Data shape: (61437, 10)

,case_id,input_text,system_label,type_label,system_pred,type_pred,system_conf,type_conf,system_strong,type_strong
0,PMC3738355_01,Littoral cell angioma mimicking hepatic tumor ...,hepatobiliary,tumor,hepatobiliary,tumor,0.997788,0.997832,hepatobiliary,tumor
1,PMC5015624_01,Central retinal artery occlusion following las...,cardiovascular,vascular,cardiovascular,vascular,0.997213,0.995973,cardiovascular,vascular
2,PMC6381877_01,Promising Combination Therapy with Bevacizumab...,respiratory,tumor,respiratory,tumor,0.999103,0.998234,respiratory,tumor
3,PMC5287946_01,Malignant adenohypophysis spindle cell oncocyt...,multisystemic,tumor,multisystemic,tumor,0.990248,0.999513,multisystemic,tumor
4,PMC9106225_01,"A novel mucocele: Myxoglobulosis [['mucocele',...",ent,trauma,ent,trauma,0.996896,0.972045,ent,trauma

In [ ]:
import zipfile
import os

zip_root = "/content/drive/MyDrive/meddiag"
extract_root = "meddiag_extracted"

os.makedirs(extract_root, exist_ok=True)

for file in os.listdir(zip_root):
    if file.endswith(".zip"):
        zip_path = os.path.join(zip_root, file)

        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_root)

        print(f"Extracted: {file}")

Extracted: PMC3.zip
Extracted: PMC2.zip
Extracted: PMC1.zip
Extracted: PMC6.zip
Extracted: PMC8.zip
Extracted: PMC5.zip
Extracted: PMC4.zip
Extracted: PMC7.zip
Extracted: PMC9.zip

In [ ]:
import os

root = "meddiag_extracted"

for folder in os.listdir(root):
    folder_path = os.path.join(root, folder)

    if not os.path.isdir(folder_path):
        continue

    print("Folder:", folder)
    print(os.listdir(folder_path)[:5])
    break

Folder: PMC1
['PMC15', 'PMC11', 'PMC10', 'PMC13', 'PMC16']

In [ ]:
import os
from collections import defaultdict

image_dict = defaultdict(list)

root = "meddiag_extracted"

for dirpath, dirnames, filenames in os.walk(root):

    for img in filenames:
        if img.endswith((".jpg", ".png", ".jpeg", ".webp")):

            case_id = img.split("_")[0]  # PMC1234567

            full_path = os.path.join(dirpath, img)
            image_dict[case_id].append(full_path)

In [ ]:
print("Total image cases:", len(image_dict))
print("Sample keys:", list(image_dict.keys())[:10])

Total image cases: 30526
Sample keys: ['PMC1550567', 'PMC1501118', 'PMC1502069', 'PMC1502064', 'PMC11722611', 'PMC11227686', 'PMC11222310', 'PMC11002164', 'PMC11091343', 'PMC11749671']

In [ ]:
df['case_id_clean'] = df['case_id'].apply(lambda x: x.split('_')[0])

df['image_paths'] = df['case_id_clean'].map(image_dict)

df['image_paths'] = df['image_paths'].apply(
    lambda x: x if isinstance(x, list) else []
)

In [ ]:
total_cases = len(df)
cases_with_images = (df['image_paths'].apply(len) > 0).sum()

print("Total cases:", total_cases)
print("Cases with images:", cases_with_images)
print("Coverage %:", cases_with_images / total_cases * 100)

Total cases: 61437
Cases with images: 26184
Coverage %: 42.61926851897066

In [ ]:
df[df['image_paths'].apply(len) > 0][['case_id','image_paths']].head(5)

         case_id                                        image_paths
1  PMC5015624_01  [meddiag_extracted/PMC5/PMC50/PMC5015624_OC-05...
2  PMC6381877_01  [meddiag_extracted/PMC6/PMC63/PMC6381877_cro-0...
3  PMC5287946_01  [meddiag_extracted/PMC5/PMC52/PMC5287946_medi-...
4  PMC9106225_01  [meddiag_extracted/PMC9/PMC91/PMC9106225_JOMFP...
5  PMC7276389_01  [meddiag_extracted/PMC7/PMC72/PMC7276389_gr2_a...

In [ ]:
df['num_images'] = df['image_paths'].apply(len)

print(df['num_images'].describe())

count    61437.000000
mean         1.783795
std          3.026386
min          0.000000
25%          0.000000
50%          0.000000
75%          3.000000
max         47.000000
Name: num_images, dtype: float64

In [ ]:
from torchvision import transforms

image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

In [ ]:
from PIL import Image
import torch

class MultiModalDataset(torch.utils.data.Dataset):
    def __init__(self, df, tokenizer, max_len=256):
        self.df = df
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # TEXT
        text = str(row['input_text'])

        enc = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_len,
            return_tensors='pt'
        )

        input_ids = enc['input_ids'].squeeze()
        attention_mask = enc['attention_mask'].squeeze()

        # IMAGE
        image_paths = row['image_paths']

        if len(image_paths) > 0:
            try:
                img = Image.open(image_paths[0]).convert("RGB")
                img = image_transform(img)
            except:
                img = torch.zeros(3, 224, 224)
        else:
            img = torch.zeros(3, 224, 224)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'image': img,
            'system_label': row['system_label'],
            'type_label': row['type_label']
        }

In [ ]:
class MultiModalDataset(torch.utils.data.Dataset):
    def __init__(self, df, tokenizer, max_len=256):
        self.df = df
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # TEXT
        text = str(row['input_text'])

        enc = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_len,
            return_tensors='pt'
        )

        input_ids = enc['input_ids'].squeeze()
        attention_mask = enc['attention_mask'].squeeze()

        # IMAGE
        image_paths = row['image_paths']

        if len(image_paths) > 0:
            try:
                img = Image.open(image_paths[0]).convert("RGB")
                img = image_transform(img)
            except:
                img = torch.zeros(3, 224, 224)
        else:
            img = torch.zeros(3, 224, 224)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'image': img,
            'system_label': torch.tensor(row['system_label_enc']),
            'type_label': torch.tensor(row['type_label_enc'])
        }

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_system = LabelEncoder()
le_type = LabelEncoder()

df['system_label_enc'] = le_system.fit_transform(df['system_strong'])
df['type_label_enc'] = le_type.fit_transform(df['type_strong'])

num_system = len(le_system.classes_)
num_type = len(le_type.classes_)

print("System classes:", le_system.classes_)
print("Type classes:", le_type.classes_)

System classes: ['cardiovascular' 'dermatological' 'endocrine' 'ent' 'gastrointestinal'
 'genetic' 'genitourinary' 'hematological' 'hepatobiliary' 'immunological'
 'lymphatic' 'multisystemic' 'musculoskeletal' 'neurological' 'ophthalmic'
 'renal' 'respiratory']
Type classes: ['autoimmune' 'degenerative' 'infection' 'metabolic' 'trauma' 'tumor'
 'vascular']

In [ ]:
from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd

from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from torchvision import models, transforms
from PIL import Image

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

from tqdm import tqdm

In [ ]:
df = pd.read_csv("/content/strong_labeled_dataset.csv")

df = df.dropna(subset=['input_text', 'system_strong', 'type_strong']).reset_index(drop=True)

print(df.shape)

(61437, 10)

In [ ]:
le_system = LabelEncoder()
le_type = LabelEncoder()

df['system_label_enc'] = le_system.fit_transform(df['system_strong'])
df['type_label_enc'] = le_type.fit_transform(df['type_strong'])

num_system = len(le_system.classes_)
num_type = len(le_type.classes_)

print(num_system, num_type)

17 7

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

In [ ]:
class MultiModalDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=256):
        self.df = df
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # TEXT
        text = str(row['input_text'])

        enc = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_len,
            return_tensors='pt'
        )

        input_ids = enc['input_ids'].squeeze()
        attention_mask = enc['attention_mask'].squeeze()

        # IMAGE
        image_paths = row['image_paths']

        if isinstance(image_paths, list) and len(image_paths) > 0:
            try:
                img = Image.open(image_paths[0]).convert("RGB")
                img = image_transform(img)
            except:
                img = torch.zeros(3, 224, 224)
        else:
            img = torch.zeros(3, 224, 224)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'image': img,
            'system_label': torch.tensor(row['system_label_enc']),
            'type_label': torch.tensor(row['type_label_enc'])
        }

In [ ]:
train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

train_dataset = MultiModalDataset(train_df, tokenizer)
val_dataset = MultiModalDataset(val_df, tokenizer)

In [ ]:
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True, num_workers=4, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=8, num_workers=4, pin_memory=True)

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

In [ ]:
class MultiModalModel(nn.Module):
    def __init__(self, num_system, num_type):
        super().__init__()

        # TEXT encoder
        self.text_encoder = AutoModel.from_pretrained("distilbert-base-uncased")
        text_dim = self.text_encoder.config.hidden_size

        # IMAGE encoder
        resnet = models.resnet18(pretrained=True)
        self.image_encoder = nn.Sequential(*list(resnet.children())[:-1])

        # 🔥 FREEZE IMAGE ENCODER
        for param in self.image_encoder.parameters():
            param.requires_grad = False

        img_dim = 512

        # FUSION
        self.fc = nn.Linear(text_dim + img_dim, 256)

        # HEADS
        self.system_head = nn.Linear(256, num_system)
        self.type_head = nn.Linear(256, num_type)

    def forward(self, input_ids, attention_mask, image):
        # TEXT
        text_out = self.text_encoder(input_ids=input_ids, attention_mask=attention_mask)
        text_emb = text_out.last_hidden_state[:, 0]

        # IMAGE
        img_feat = self.image_encoder(image)
        img_feat = img_feat.view(img_feat.size(0), -1)

        # FUSION
        combined = torch.cat([text_emb, img_feat], dim=1)
        x = self.fc(combined)

        return self.system_head(x), self.type_head(x)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = MultiModalModel(num_system, num_type).to(device)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth

100%|██████████| 44.7M/44.7M [00:00<00:00, 121MB/s]

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=2e-5)

In [ ]:
from collections import defaultdict
import os

image_dict = defaultdict(list)

root = "meddiag_extracted"

for dirpath, _, filenames in os.walk(root):
    for img in filenames:
        if img.endswith((".jpg", ".png", ".jpeg", ".webp")):
            case_id = img.split("_")[0]
            full_path = os.path.join(dirpath, img)
            image_dict[case_id].append(full_path)

In [ ]:
df['case_id_clean'] = df['case_id'].apply(lambda x: x.split('_')[0])

df['image_paths'] = df['case_id_clean'].map(image_dict)

df['image_paths'] = df['image_paths'].apply(
    lambda x: x if isinstance(x, list) else []
)

In [ ]:
print("Column exists:", 'image_paths' in df.columns)

print("Samples with images:",
      (df['image_paths'].apply(len) > 0).sum())

Column exists: True
Samples with images: 26184

In [ ]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

In [ ]:
train_dataset = MultiModalDataset(train_df, tokenizer)
val_dataset = MultiModalDataset(val_df, tokenizer)

In [ ]:
train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    num_workers=2,   # 🔥 change from 4 → 2
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    num_workers=2,
    pin_memory=True
)

In [ ]:
EPOCHS = 3

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}")

    for batch in progress_bar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        images = batch['image'].to(device)

        sys_labels = batch['system_label'].to(device)
        type_labels = batch['type_label'].to(device)

        optimizer.zero_grad()

        sys_logits, type_logits = model(input_ids, attention_mask, images)

        loss_sys = criterion(sys_logits, sys_labels)
        loss_type = criterion(type_logits, type_labels)

        loss = loss_sys + loss_type

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        progress_bar.set_postfix(loss=loss.item())

    print(f"\nEpoch {epoch+1} DONE | Total Loss: {total_loss:.4f}")

Epoch 1: 100%|██████████| 6912/6912 [24:26<00:00,  4.71it/s, loss=0.911]

Epoch 1 DONE | Total Loss: 8126.3706

Epoch 2: 100%|██████████| 6912/6912 [24:32<00:00,  4.69it/s, loss=0.0568]

Epoch 2 DONE | Total Loss: 3979.9135

Epoch 3: 100%|██████████| 6912/6912 [24:30<00:00,  4.70it/s, loss=0.164]

Epoch 3 DONE | Total Loss: 2689.4233

In [ ]:
model.eval()

sys_preds, sys_true = [], []
type_preds, type_true = [], []

with torch.no_grad():
    for batch in val_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        images = batch['image'].to(device)

        sys_labels = batch['system_label'].to(device)
        type_labels = batch['type_label'].to(device)

        sys_logits, type_logits = model(input_ids, attention_mask, images)

        sys_pred = torch.argmax(sys_logits, dim=1)
        type_pred = torch.argmax(type_logits, dim=1)

        sys_preds.extend(sys_pred.cpu().numpy())
        sys_true.extend(sys_labels.cpu().numpy())

        type_preds.extend(type_pred.cpu().numpy())
        type_true.extend(type_labels.cpu().numpy())

print("System F1:", f1_score(sys_true, sys_preds, average='macro'))
print("Type F1:", f1_score(type_true, type_preds, average='macro'))

System F1: 0.820222103514724
Type F1: 0.860137979274082

In [ ]:
torch.save(model.state_dict(), "multimodal_model.pt")

In [ ]:
from google.colab import files

files.download("multimodal_model.pt")