In [ ]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

csv_path = "/content/drive/MyDrive/meddiag/multimodal_cases.csv"

df = pd.read_csv(csv_path)

print(df.shape)
df.head()

(61437, 30)

,age,case_id,case_text,gender,article_id,image_files,image_captions,image_components,case_substrings,image_types,...,title,journal,year,doi,keywords,mesh_terms,major_mesh_terms,authors,license,abstract
0,53.0,PMC3738355_01,A 53-year-old woman presented with a 10-year h...,Female,PMC3738355,NaN,NaN,NaN,NaN,NaN,...,Littoral cell angioma mimicking hepatic tumor,Acta Radiol Short Rep,2012,10.1258/arsr.2012.120031,"[['vascular tumor', 'diagnostic imaging', 'liv...",[['Case Reports']],[[]],"[['Wenhua Liang', 'Jingjing Lu', 'Mingwei Qin'...",CC BY-NC,Littoral cell angioma is a rare vascular tumor...
1,69.0,PMC5015624_01,A 69-year-old Caucasian female with coronary a...,Female,PMC5015624,['PMC5015624_OC-05-14-g-001_undivided_1_1.webp...,['Slit lamp biomicroscopy of the anterior segm...,"['undivided', 'undivided']","[['Figure 1', 'Fig. 1'], ['Figure 4', 'Fig. 4']]","['endoscopy', 'radiology']",...,Central retinal artery occlusion following las...,GMS Ophthalmol Cases,2015,10.3205/oc000036,"[['mri', 'aortic arch', 'carotid artery stenos...",[['Case Reports']],[[]],"[['Payal J Shah', 'Brian Ellis', 'Lauren R DiG...",CC BY,Objective: Ocular ischemic syndrome is a rare ...
2,60.0,PMC6381877_01,A 60-year-old male smoker presented with persi...,Male,PMC6381877,"['PMC6381877_cro-0012-0091-g01_a_1_2.webp', 'P...",['Chest X-ray and chest CT images before initi...,"['a', 'b', 'a', 'b']","[['Fig. 1a, b'], ['Fig. 1a, b'], ['Fig. 2a, b'...","['radiology', 'radiology', 'radiology', 'radio...",...,Promising Combination Therapy with Bevacizumab...,Case Rep Oncol,2019,10.1159/000493088,"[['bevacizumab', 'egfr mutation', 'erlotinib',...",[['Case Reports']],[[]],"[['Nobuhiko Seki', 'Maika Natsume', 'Ryosuke O...",CC BY-NC,"In lung cancer, several potential mechanisms o..."
3,30.0,PMC5287946_01,A 30-year-old man came to Peking Union Medical...,Male,PMC5287946,"['PMC5287946_medi-96-e5657-g002_A_1_12.webp', ...",['Histopathological and immunohistochemical ex...,"['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', ...","[['Fig. 2A-K'], ['Fig. 2A-K'], ['Fig. 2A-K'], ...","['pathology', 'pathology', 'pathology', 'patho...",...,Malignant adenohypophysis spindle cell oncocyt...,Medicine (Baltimore),2017,10.1097/MD.0000000000005657,NaN,"[['Adenoma, Oxyphilic / pathology', 'Ki-67 Ant...","[['Adenoma, Oxyphilic / pathology', 'Ki-67 Ant...","[['Xiangyi Kong', 'Dongmei Li', 'Yanguo Kong',...",CC BY,Adenohypophysis spindle cell oncocytoma (ASCO)...
4,40.0,PMC9106225_01,A 40-year-old female patient was referred for ...,Female,PMC9106225,['PMC9106225_JOMFP-26-101-g001_undivided_1_1.w...,"['Clinical image shows a well-defined, roughly...","['undivided', 'undivided', 'undivided', 'undiv...","[['Figure 1'], ['Figure 2'], ['Figure 3', 'Fig...","['pathology', 'pathology', 'pathology', 'patho...",...,A novel mucocele: Myxoglobulosis,J Oral Maxillofac Pathol,2022,10.4103/jomfp.jomfp_214_21,"[['mucocele', 'mucus extravasation cyst', 'myx...",[['Case Reports']],[[]],"[['Rutuja Gajanan Vidhale', 'Subraj Shetty', '...",CC BY-NC-SA,Oral extravasation mucoceles are among the mos...

In [ ]:
SYSTEM_LABELS = [
    "neurological",
    "cardiovascular",
    "respiratory",
    "musculoskeletal",
    "hematological",
    "hepatobiliary",
    "gastrointestinal",
    "genitourinary",
    "renal",
    "lymphatic",
    "immunological",
    "dermatological",
    "ophthalmic",
    "ent",   # ear nose throat
    "endocrine",
    "multisystemic"
]

In [ ]:
def build_input(row):
    age = str(row.get('age', ''))
    gender = str(row.get('gender', ''))

    return (
        f"Age: {age}. Gender: {gender}. " +   #  structured context
        str(row.get('title', '')) + " " +
        str(row.get('keywords', '')) * 2 + " " +
        str(row.get('abstract', '')) + " " +
        str(row.get('image_captions', ''))
    )

In [ ]:
df['input_text'] = df.apply(build_input, axis=1)

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
system_emb = model.encode(SYSTEM_LABELS)

In [ ]:
def predict_system(text):
    emb = model.encode([text])[0]
    sims = np.dot(system_emb, emb)
    return SYSTEM_LABELS[np.argmax(sims)]

In [ ]:
from tqdm import tqdm

batch_size = 64
texts = df['input_text'].tolist()

system_preds = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i+batch_size]

    emb = model.encode(batch)
    sims = np.dot(emb, system_emb.T)

    preds = [SYSTEM_LABELS[np.argmax(s)] for s in sims]
    system_preds.extend(preds)

df['system_label'] = system_preds

100%|██████████| 960/960 [03:26<00:00,  4.65it/s]

75% correct

In [ ]:
df[['title', 'system_label']].sample(20)

                                                   title      system_label
28104  IVIG Associated Aseptic Meningitis in a Renal ...             renal
31208  Syphilis: an atypical case of sepsis and multi...     immunological
8508   Chronic Urinary Retention due to Fowler's Synd...             renal
34247  Clinical Profile and Outcome of Esophageal But...  gastrointestinal
45938  Mycobacterium chelonae cutaneous infection in ...    dermatological
19416  Sequential Keraring implantation and corneal c...        ophthalmic
3799   Xanthogranulomatous Pyelonephritis: Synchronou...             renal
37438  Nasopharyngeal Angiofibroma: A Forgotten Entit...       respiratory
29781  Successful Expectant Management of the Anomalo...     multisystemic
29373   An Erupted Dilated Odontoma: A Rare Presentation        ophthalmic
559    Reconstruction of the Peroneus Brevis Tendon T...   musculoskeletal
38913  Laparoscopic Reduction and Closure of an Inter...  gastrointestinal
21062      Twin gestation in a septate bicornuate uterus     genitourinary
10182  Hybrid ameloblastoma: An amalgam of rare and c...     hematological
37947  Xerophthalmia: Findings from the Eye Lead to D...        ophthalmic
61300  Granulomatosis with polyangiitis with cardiac ...    cardiovascular
38636  CUP-syndrome: Inguinal high grade serous ovari...         lymphatic
34138  Caloric Vestibular Stimulation Reduces Pain an...      neurological
36410  Maternal sirolimus therapy and fetal growth re...         lymphatic
2844   Case report: desensitization of hypersensitivi...    dermatological

In [ ]:
def system_rule_boost(text):
    text = str(text).lower()

    #  STRONG organ keywords

    # neurological
    if any(x in text for x in ['brain', 'mening', 'neuro', 'spinal', 'arachnoid']):
        return 'neurological'

    # cardiovascular
    if any(x in text for x in ['heart', 'cardiac', 'aortic']):
        return 'cardiovascular'

    # respiratory
    if any(x in text for x in ['lung', 'pulmonary']):
        return 'respiratory'

    # hepatobiliary
    if any(x in text for x in ['liver', 'hepatic']):
        return 'hepatobiliary'

    #  NEW: spleen → NOT hepatobiliary
    if 'spleen' in text or 'splenic' in text:
        return 'hematological'

    # renal
    if any(x in text for x in ['kidney', 'renal', 'neph']):
        return 'renal'

    # dermatological (important for infections)
    if any(x in text for x in ['skin', 'cutaneous', 'bite', 'wound']):
        return 'dermatological'

    # ophthalmic
    if any(x in text for x in ['eye', 'retina', 'cornea', 'ophthalm']):
        return 'ophthalmic'

    # ENT
    if any(x in text for x in ['nasal', 'sinus', 'oral', 'tooth', 'dental']):
        return 'ent'

    # genitourinary
    if any(x in text for x in ['uterus', 'ovary', 'prostate', 'bladder']):
        return 'genitourinary'

    # musculoskeletal
    if any(x in text for x in ['bone', 'muscle', 'tendon', 'fracture']):
        return 'musculoskeletal'

    # genetic / syndrome
    if 'syndrome' in text:
        return 'genetic'

    # drug / therapy → multisystemic
    if any(x in text for x in ['therapy', 'treatment', 'drug']):
        return 'multisystemic'

    return None

In [ ]:
def predict_system_final(text):
    rule = system_rule_boost(text)

    if rule:
        return rule

    return predict_system(text)

In [ ]:
df['system_label'] = df['input_text'].apply(predict_system_final)

In [ ]:
df[['title','system_label']].sample(20)

                                                   title     system_label
61242  Human amniotic membrane graft removal and hist...       ophthalmic
47308  Splenic metastasis of ovarian clear cell adeno...    hepatobiliary
31674  An adult patient with Nijmegen Breakage Syndro...        lymphatic
22188              Gynecomastia and Klinefelter Syndrome    genitourinary
806    Effect of Pravastatin as an Adjunctive Therape...     neurological
33567  Accelerated recovery of sensorimotor function ...              ent
25239  Immunocheckpoint Inhibitor- (Nivolumab-) Assoc...      respiratory
37929  Successful Removal of a Posterior Cardiac Lipo...   cardiovascular
10679  Rare dorsal thoracic arachnoid web mimics spin...     neurological
21854  Endoscopic Endonasal Transclival Approach to V...     neurological
58734  An Infected Dog Bite With Neisseria animaloris...     neurological
34561  Aortic calcification in Gaucher disease: a cas...   cardiovascular
15864  Significant response of pulmonary sarcomatoid ...      respiratory
21135  Umbilical Myiasis by Cochliomyia hominivorax i...              ent
59691  Renal pseudotumor mimicking renal cell carcino...      respiratory
20173  Novel Compound Heterozygous Variants of ETHE1 ...     neurological
7397   Hypoparathyroidism, deafness and renal dysplas...            renal
53020  A Case of Superficial Kaposiform Hemangioendot...              ent
41373  Magnesium-Based Absorbable Metal Screws for In...  musculoskeletal
40290  Acute Traumatic Tear of the Gluteus Medius and...  musculoskeletal

In [ ]:
def predict_system_final(text):
    text = str(text)

    #  Step 1: model prediction
    emb = model.encode([text])[0]
    sims = np.dot(system_emb, emb)

    model_pred = SYSTEM_LABELS[np.argmax(sims)]
    model_conf = np.max(sims)

    #  Step 2: rule prediction
    rule_pred = system_rule_boost(text)

    #  Step 3: combine logic

    # case 1: no rule → trust model
    if rule_pred is None:
        return model_pred

    # case 2: strong model confidence → trust model
    if model_conf > 0.6:
        return model_pred

    # case 3: otherwise use rule
    return rule_pred

In [ ]:
from tqdm import tqdm

batch_size = 64
texts = df['input_text'].tolist()

final_preds = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i+batch_size]

    #  model embeddings (batch)
    emb = model.encode(batch)
    sims = np.dot(emb, system_emb.T)

    model_preds = [SYSTEM_LABELS[np.argmax(s)] for s in sims]
    model_confs = [np.max(s) for s in sims]

    #  rule predictions
    rule_preds = [system_rule_boost(t) for t in batch]

    #  combine
    batch_preds = []

    for mp, mc, rp in zip(model_preds, model_confs, rule_preds):

        if rp is None:
            batch_preds.append(mp)

        elif mc > 0.6:
            batch_preds.append(mp)

        else:
            batch_preds.append(rp)

    final_preds.extend(batch_preds)

100%|██████████| 960/960 [03:08<00:00,  5.08it/s]

In [ ]:
df['system_label'] = final_preds

In [ ]:
print(df['system_label'].value_counts())

system_label
neurological        13034
multisystemic        6221
dermatological       6069
cardiovascular       5264
respiratory          5247
ent                  4751
hepatobiliary        4221
renal                3699
musculoskeletal      3307
ophthalmic           2307
genetic              2036
genitourinary        1625
gastrointestinal     1218
hematological        1146
immunological         699
lymphatic             496
endocrine              97
Name: count, dtype: int64

In [ ]:
df[['title','system_label']].sample(50)

                                                   title      system_label
42247                Patient with Morning Glory syndrome         endocrine
58828  Hereditary exostosis: An unexpected malignant ...   musculoskeletal
52438  Lung Abscess Caused by Tannerella forsythia In...       respiratory
48880   Noninvasive fungal rhinosinusitis: a case series               ent
26280  Novel approach for phacoemulsification during ...        ophthalmic
20846  Predictors of Complications and Unfavorable Ou...      neurological
46685  Sudden Cardiac Death: The Most Feared but Pote...    cardiovascular
17367  Very Rare Presentation of Cerebrovascular Acci...      neurological
59089  Incarcerated peri-inguinal hernia containing t...     hematological
7747   Periprosthetic proximal medial femoral cortica...               ent
1770   A Brisk and Life-Saving Diagnosis of Pericardi...       respiratory
36593                             Jejunal diverticulitis  gastrointestinal
36423  Neonatal acute liver failure with pulmonary ye...      neurological
44969  The treatment of a Morel-Lavallée lesion of th...    dermatological
56777  Long-term disease stability with bicalutamide ...     immunological
37611  A case of reactive arthritis due to Clostridiu...  gastrointestinal
8169    Serotonin syndrome presenting as pulmonary edema      neurological
13895  Phthirus pubis Infestation of the Eyelids Pres...        ophthalmic
43993  Ceramic Laminate Veneers for Reestablishment o...        ophthalmic
58648  Case report: Immunotherapy in rare high TMB pa...    dermatological
43465  Wireless Patrol Sign-In System with Mental Fat...   musculoskeletal
14112  Acute ulnar nerve compression associated with ...   musculoskeletal
33800  Antipsychotic drugs may contribute to venous t...      neurological
13693    Non-invasive management of fused upper incisors               ent
51572  A Rare Case of Neurosyphilis with Calvaria Ost...      neurological
4134   Intrahepatic Cholestasis of Pregnancy Leading ...     hepatobiliary
37291  Multi-System Langerhans Cell Histiocytosis as ...     hepatobiliary
42796  A Novel Silent Mutation in the L1CAM Gene Caus...         lymphatic
16389  Duodenal duplication: a rare cause of abdomina...  gastrointestinal
35915  Successful treatment with HLA-matched peripher...     hematological
9011   Subcutaneous Olanzapine at the End of Life in ...    dermatological
14851  Profuse coarse pulmonary nodules in a patient ...       respiratory
23161  Stevens-johnson syndrome induced by carbamazep...    dermatological
47356  Primary CNS vasculitis masquerading as gliobla...      neurological
1215   Stercoral perforation proximal to the stapled ...               ent
9354   A Case of Proliferative Glomerulonephritis wit...             renal
43174  A case of NK/T-cell lymphoma complicated by a ...               ent
6079   VATS bullectomy and apical pleurectomy for spo...       respiratory
45526     Seizure Mimicking Stroke: Role of CT Perfusion      neurological
59762  Comparing Care Pathways Between COVID-19 Pande...       respiratory
48131  Multi-Modality Imaging Approach to a rare form...    cardiovascular
55869  Case report: A novel COL3A1 variant in a Colom...      neurological
36557  Hereditary Hypercalcemia Caused by a Homozygou...             renal
31495  Intestinal metastasis from breast invasive duc...  gastrointestinal
46939  Minimal-Change Disease Secondary to Borrelia b...             renal
39655  Postoperative intussusception in a neonate wit...    dermatological
3276   Cor triatriatum dexter: A rare cause of childh...    cardiovascular
13221  Progression to macula-off tractional retinal d...        ophthalmic
24537  Multiple oral leiomyomas in an infant: a rare ...    dermatological
30135  Case Report: Dacomitinib Overcomes Osimertinib...      neurological

In [ ]:
import pandas as pd

pd.set_option('display.max_colwidth', None)  #  show full text

In [ ]:
df[['input_text', 'system_label']].sample(50)

,input_text,system_label
42903,"Severe arrhythmia induced by orally disintegrating aripiprazole tablets (Bosiqing(®)): a case report [['antipsychotics', 'aripiprazole', 'arrhythmia', 'schizophrenia']][['antipsychotics', 'aripiprazole', 'arrhythmia', 'schizophrenia']] Psychotropic medications have been known to cause cardiac conduction disturbances. Not much is known about the cardiovascular side effects of newer atypical antipsychotics such as aripiprazole. A case of a 13-year-old girl with schizophrenia is presented. An analysis of the presented patient's clinical history indicates the need for a detailed analysis of the severe arrhythmia induced by aripiprazole. This presented case report contains valuable guidelines that can be of assistance in the treatment of patients with aripiprazole.",cardiovascular
29974,"Bedside Carotid Sinus Massage for Syncope Evaluation With Bifascicular Block and First-Degree Atrioventricular Block [['atrioventricular block', 'bifascicular block', 'cardiac syncope', 'carotid sinus massage', 'permanent pacemaker']][['atrioventricular block', 'bifascicular block', 'cardiac syncope', 'carotid sinus massage', 'permanent pacemaker']] Symptomatic bifascicular block (BFB) with a reversible high-grade atrioventricular block (AVB) is an overlooked cause of syncope with differing diagnostic and therapeutic approaches. We present a case of a 79-year-old gentleman with multiple episodes of cardiac syncope. Initial electrocardiogram revealed a left bundle branch block and first-degree AVB worsened by bedside carotid sinus massage (CSM) obviating the need for electrophysiologic (EP) studies or continuous electrocardiographic monitoring for further evaluation. This case highlights the importance of CSM as a useful clinical tool in addition to EP studies and internal loop recorder (ILR) placement for assessment and appropriateness of permanent pacemaker (PPM) implantation. It also sheds light on the differing management protocols between EP studies and ILR evaluation versus empiric PPM implantation for patients with cardiac syncope secondary to BFB and AVB.",cardiovascular
13547,"A Case Report of Cannabis Abuse: A Surprising Etiology of Elevated Troponin [['']][['']] Cannabis is the most commonly used additive drug after alcohol and tobacco. There has been literature proving the relationship between cannabis use and elevated troponin from myocardial infarction, with many mechanisms explaining them. However, limited data are available on elevated troponin due to cannabis-induced high myocardial oxygen demand due to vasospasm. We present a case of a 21-year-old female presenting with chest pain after cannabis abuse. She exhibited a steep rise in troponin with a normal electrocardiogram (EKG). She refused a coronary angiogram, but a bedside echocardiogram showed no wall motion abnormality. Therefore, the dramatic rise of troponin levels with the chest pain and the resolution of the symptoms were most likely explained by demand ischemia via the mechanism of reversible vasospasm.",cardiovascular
20049,"Potential Adverse Consequences of Combination Therapy with Gabapentin and Pregabalin nannan Gabapentinoids comprise the medications gabapentin and pregabalin. These were designed to not only look chemically like the central inhibitory neurotransmitter gamma-aminobutyric acid (GABA) but also act like it. The prototype gabapentin was primarily introduced to be used as antiepileptic medication. Today, both chemicals are not only utilized as adjunct antiepileptics in focal (aware and impaired awareness) seizures but are also used in several neuropathic pain conditions and other clinical indications. Their use has skyrocketed in the past few years and this has brought forward more instances of adverse effects and errors in prescribing practices. We describe here a case of a female patient with a history of diabetes, diabetic neuropathy, and hypertension being prescribed both gabapentin and pregabalin concomitantly which led to adverse effects like drowsiness, dizziness, fatigue, and ataxia. Once the patient medication profile was revisited, the pharmacy staff was able to identify the therapeutic duplications (gabapentin and pregabalin). The physician was contacted and pregabalin was discontinued. This led to the disappearance of the adverse effects. The dose of the existing gabapentin was increased to control the symptoms of diabetic neuropathy. This report sheds light on the importance of responsible prescribing, efficient checking of medication profiles on the level of dispensing pharmacies, and timely follow-up to patients to keep the patients safe and their medical conditions under check.",neurological
15127,"Solid pseudopapillary neoplasm of the pancreas with multiple liver metastases successfully managed with staged resection [['solid pseudopapillary neoplasm', 'case report', 'liver metastasis', 'pancreas', 'staged resection']][['solid pseudopapillary neoplasm', 'case report', 'liver metastasis', 'pancreas', 'staged resection']] Due to the rarity of the disease, there are no guidelines or consensus for the management of solid pseudopapillary neoplasm of the pancreas with liver metastasis. We describe a patient with solid pseudopapillary neoplasm of the pancreas with multiple liver metastases who was successfully managed with staged resection. A previously healthy 50-year-old female presented to the clinic with dull epigastric pain. The contrast-enhanced computed tomography showed a well-defined cystic lesion at the distal body and tail of the pancreas with multiple liver deposits. A core needle liver biopsy was suspicious of a hepatic epithelioid hemangioendothelioma. A distal pancreatectomy with splenectomy and a left hemi-hepatectomy were performed with a subsequent staged right posterior sectionectomy to address the inadequate future liver remnant. The final histology with immunohistochemistry revealed a pancreatic solid pseudopapillary neoplasm. The patient had satisfactory surgical and oncological outcomes with no recurrence. As these are slow growing tumours, appropriately spaced staged liver resection was feasible to allow hypertrophy of the liver remnant and physiological recovery of the patient. The discrepancy in the histology and cross-sectional imaging led to a pre-operative diagnostic dilemma, and the final diagnosis was reached after surgical resection. Thus, resectable metastatic solid pseudopapillary neoplasm of the pancreas may be offered a primary curative radical surgery before considering other treatment modalities.",hepatobiliary
15905,"Horn on the Nail: Acquired Ungual Fibrokeratoma [['garlic clove', 'horn like', 'ungual fibrokeratoma']][['garlic clove', 'horn like', 'ungual fibrokeratoma']] Acquired ungual fibrokeratomas are uncommon fibrous tissue tumors that are located in the ungual area. They usually presents as asymptomatic, solitary, smooth, dome-shaped, or fingerlike, flesh-colored papules accompanying nail deformities, including a longitudinal groove and trachyonychia. Acquired periungual fibrokeratoma is considered a topographical variant of acquired digital fibrokeratoma; it has a unique ""garlic clove"" shape. A traumatic origin has been suggested, as acquired ungual fibrokeratomas occur most frequently on the fingers and toes. Herein, we report a case of a 29-year-old man with growth over left little finger, who was treated with surgical excision of the tissue. Histopathological examination confirmed ungual fibrokeratoma. It is a rare variant of digital fibrokeratoma, and so far the first ungual fibrokeratoma to appear de novo on little finger to the best of our knowledge.",dermatological
1627,"Abdominal compartment syndrome after endoscopic combined intrarenal surgery [['abdominal compartment syndrome', 'endoscopic combined intrarenal surgery', 'hydroperitoneum', 'percutaneous nephrolithotripsy', 'staghorn calculus']][['abdominal compartment syndrome', 'endoscopic combined intrarenal surgery', 'hydroperitoneum', 'percutaneous nephrolithotripsy', 'staghorn calculus']] Introduction: We report a case of abdominal compartment syndrome due to hydroperitoneum after endoscopic combined intrarenal surgery. Case presentation: A 56-year-old woman with a left staghorn calculus underwent endoscopic combined intrarenal surgery as a two-staged procedure and developed a distended abdomen, cyanosis of both legs, and hypotension immediately after the second operation. A computed tomography scan showed hydroperitoneum. We performed urgent laparotomy and evacuated approximately 2 L of nearly transparent fluid. No peritoneal injury was detected. Postoperatively, she required intensive care for shocked liver and acute kidney injury. Conclusion: Hydroperitoneum after endoscopic combined intrarenal surgery is a rare complication and may lead to abdominal compartment syndrome or a condition where intra-abdominal pressure exceeds 20 mmHg, causing impaired organ perfusion. Delayed drainage can be fatal.",hepatobiliary
40716,"Ruptured seminoma of undescended testis presenting as acute abdomen: case report with literature review [['acute abdomen', 'cryptorchidism', 'intra-abdominal seminoma']][['acute abdomen', 'cryptorchidism', 'intra-abdominal seminoma']] We present a case of a 28-year-old male who presented with acute abdomen and was later diagnosed to be having ruptured intra-abdominal seminoma with hemoperitoneum, where the pre-operative diagnosis was not made. Laprotomy and complete excision were carried out. Rupture of intra-abdominal testicular seminoma is a rare cause of acute abdomen and hemoperitoneum. The pre-operative diagnosis is often difficult because history of cryptorchidism is not provided and imaging findings may be non-specific. In a male patient with acute abdomen and without previous history of orchidectomy, a testicular aetiology of acute abdomen should be kept as the differential diagnosis.",hematological
38460,"Use of Aminocaproic Acid in Combination With Extracorporeal Membrane Oxygenation in a Case of Leptospirosis Pulmonary Hemorrhage Syndrome [['ecmo', 'leptospirosis', 'aminocaproic acid', 'pulmonary hemorrhage']][['ecmo', 'leptospirosis', 'aminocaproic acid', 'pulmonary hemorrhage']] A 32-year-old man presented with a 10-day history of fever, chills, nausea, vomiting, myalgia, nonproductive cough, and worsening dyspnea after freshwater swimming in the Caribbean 1 week prior to presentation. Shortly after arrival at the hospital, the patient developed severe respiratory distress with massive hemoptysis. Based on serologic workup, he was diagnosed with leptospirosis pulmonary hemorrhage syndrome leading to diffuse alveolar hemorrhage, severe hypoxemic respiratory failure, and multiorgan failure. He received appropriate antibiotic coverage along with hemodynamic support with norepinephrine and vasopressin, mechanical ventilation, and renal replacement therapy in an intensive care unit. Introduction of extracorporeal membrane oxygenation was initiated to provide lung-protective ventilation supporting the recovery of his pulmonary function. Aminocaproic acid was used to stop and prevent further alveolar hemorrhage. He fully recovered thereafter; however, it is uncertain whether it was the use of aminocaproic acid that led to the resolution of his disease.",respiratory
37033,"Syndrome in question. Brooke-Spiegler syndrome nannan Brooke-Spiegler syndrome is an autosomal dominant disorder with variable penetrance and expression. It is characterized by a genetic predisposition to develop multiple adnexal neoplasias: cylindromas, trichoepitheliomas, and trichoblastomas. We describe a 54-year-old male patient with cylindromas, trichoepitheliomas, and trichoblastoma.",dermatological
52193,"Identifying Chili as a Risk Factor for the Geographic Tongue: A Case Report [['gtasi', 'ige', 'allergy', 'prick test', 'spicy food']][['gtasi', 'ige', 'allergy', 'prick test', 'spicy food']] Introduction: Geographic tongue (GT) is a chronic tongue condition triggered by various factors such as immune reactions, allergies, stress, hereditary factors, and nutritional deficiencies. The prevalence of GT in the population ranges from 1% to 3%, and its symptoms can cause discomfort to patients. Spicy foods are popular among Indonesians. Chili is one such food that can cause allergies and trigger GT. Objective: This report highlights the significance of identifying the risk factors associated with symptomatic GT. Case: A 19-year-old female patient complained of a rough and sore dorsal tongue for a year, particularly after consuming spicy food. Extra-oral examination revealed dry lips. Intra-oral examination showed red patches with white borders on the dorsal tongue. A complete blood count and allergy test were performed. The eosinophil count was 4%, the total IgE level was 698 IU/mL, and the skin prick test for chili was positive. The diagnosis of chili-induced GT was made. Case management: The patient was advised to avoid chilies, and benzydamine hydrochloride mouthwash was administered. One week after treatment, clinical improvement was observed. Severity decreased on the Geographic Tongue Area and Severity Index (GTASI) from 12 (moderate) to 0.4 (mild). Pain decreased from 6 to 0 on the numerical rating scale (NRS). Conclusion: Management of symptomatic GT includes the avoidance of allergens such as chilies and appropriate pharmacological therapy. The identification of risk factors is required for effective management.",dermatological
46890,"A Case of Sparganosis mansoni in the Thigh: Serological Validation of Cure Following Surgery [['elisa', 'sparganosis', 'surgery', 'ultrasonography']][['elisa', 'sparganosis', 'surgery', 'ultrasonography']] Cases of Sparganum mansoni, caused by the plerocercoid larva of the tapeworm S. mansoni, occur throughout the world, particularly in Asian, Middle Eastern, and European countries. However, cases of infection with this parasite are rarely seen in Japan. Here, we present a case of a 61-year-old woman with a solitary subcutaneous nodule in left inner aspect of the thigh, from which a long, slender, whitish worm was surgically removed. The parasite was histopathologically identified as S. mansoni. Serological testing confirmed cure of the infection after surgical removal of the parasite. The authors advocate immunoserological examination in case of S. mansoni.",dermatological
29091,"Spontaneous resolution of subfoveal perfluorocarbon [['perfluorocarbon', 'resolution', 'retained', 'subretinal']][['perfluorocarbon', 'resolution', 'retained', 'subretinal']] Perfluorocarbon liquids (PFCL) have transformed the surgical approach to complex retinal detachments, but their use can be complicated by subretinal retention. Migration of peripherally located subretinal PFCL towards the fovea is well established, but spontaneous resolution of subfoveal PFCL without surgical evacuation or displacement has rarely been described. We present a case of a large single retained subfoveal PFCL droplet following vitrectomy with membrane peeling, inferior relaxing retinectomy, and silicone oil tamponade that demonstrated spontaneous resolution 3 weeks postoperatively, with subsequent anatomic and visual improvement. No residual subretinal PFCL was noted, and we hypothesize that the PFCL droplet spontaneously extruded through a transient hole created in the thinned retina overlying the droplet, which subsequently closed spontaneously. Further understanding of the mechanisms of PFCL migration and resolution may facilitate improved treatments for this complication.",ophthalmic
995,"Kawasaki Disease With Combined Cholestatic Hepatitis and Mycoplasma pneumoniae Infection: A Case Report and Literature Review [['kawasaki disease (kd)', 'mycoplasma pneumoniae infection', 'abdominal pain', 'cholestatic hepatitis', 'jaundice']][['kawasaki disease (kd)', 'mycoplasma pneumoniae infection', 'abdominal pain', 'cholestatic hepatitis', 'jaundice']] Kawasaki disease (KD), also called mucocutaneous lymph node syndrome, is a febrile multisystem vasculitis mainly affecting children younger than 5 years. KD typically manifests as skin lesions and in the lymph nodes and oral and conjunctival mucosa. It may induce coronary artery abnormalities, such as aneurysms, but gastrointestinal and hepatobiliary involvement are not common. We reviewed 32 cases of patients with a diagnosis of KD with hepatobiliary involvement between 2000 and 2021 and present the case of a 4-year-old girl who received a diagnosis of KD with combined cholestatic hepatitis and Mycoplasma pneumoniae infection. In the 33 cases reviewed, in addition to the classical clinical findings of KD, the most common clinical presentations were jaundice and abdominal pain. Moreover, abnormal laboratory results indicating hyperbilirubinemia, cholestasis, and hepatitis, among other conditions, were noted. Abdominal ultrasonography revealed abnormal findings in more than half children with KD with hepatobiliary involvement. Furthermore, cardiac involvement was noted in a high proportion of the patients. In particular, we noted the case of a 4-year-old girl with a rare presentation of 3-day fever combined with abdominal pain and jaundice. Her levels of aspartate aminotransferase, alanine aminotransferase, total bilirubin, direct bilirubin, alkaline phosphatase, and γ-glutamyl transpeptidase were 489 (15-50) U/L, 253 (5-45) U/L, 4.3 (<1.5) mg/dl, 2.4 (<0.2) mg/dl, 337 (134-315) U/L, and 145 (5-32) U/L, respectively. These results were indicative of cholestatic hepatitis. Furthermore, her serological test results for mycoplasma infection were positive. KD was diagnosed because the patient had high fever for more than 5 days and presented with lymphadenopathy on the left side of neck, a polymorphic skin rash, redness of oral mucosa with strawberry tongue, and nonpurulent conjunctival congestion. After intravenous immunoglobulin injection (IVIG) and acetylsalicylic acid administration, the fever subsided rapidly and clinical manifestations, such as jaundice and abdominal pain, were mitigated. The laboratory parameters gradually returned to within normal ranges. Echocardiography revealed no aneurysm. In conclusion, KD with cholestatic hepatitis should be considered when pediatric patients present with fever combined with abdominal pain and jaundice. Early treatment with IVIG and aspirin is recommended and can effectively relieve cholestatic hepatitis.",cardiovascular
46126,"Poly-microbial Clostridium cadaveris bacteremia in an immune-compromised patient nannan Clostridium cadaveris (C. cadaveris), a strict anaerobic gram-positive rod, is rarely reported in clinical specimens. Since its detection in 1899, it has always been linked to the decay of dead bodies. C. cadaveris is considered non-pathogenic to humans, however infrequently it can cause severe infections including bacteremia. The latter was typically associated with gastro-intestinal pathologies. We report the first case of C. cadaveris invasive infection at Sultanate Oman. The source was most probably an infected decubitus ulcer.",gastrointestinal

In [ ]:
TYPE_LABELS = [
    "tumor",
    "infection",
    "vascular",
    "metabolic",
    "degenerative",
    "trauma",
    "autoimmune"
]

In [ ]:
def type_rule_boost(text):
    text = str(text).lower()

    # tumor
    if any(x in text for x in [
        'cancer', 'carcinoma', 'tumor', 'sarcoma',
        'neoplasm', 'metastasis', 'adenoma'
    ]):
        return 'tumor'

    # infection
    if any(x in text for x in [
        'infection', 'bacteria', 'viral', 'fungal',
        'sepsis', 'abscess', 'tuberculosis'
    ]):
        return 'infection'

    # vascular
    if any(x in text for x in [
        'stroke', 'aneurysm', 'thrombosis', 'embolism'
    ]):
        return 'vascular'

    # metabolic
    if any(x in text for x in [
        'diabetes', 'metabolic', 'obesity'
    ]):
        return 'metabolic'

    # trauma
    if any(x in text for x in [
        'injury', 'fracture', 'trauma'
    ]):
        return 'trauma'

    # autoimmune
    if any(x in text for x in [
        'autoimmune', 'lupus', 'arthritis'
    ]):
        return 'autoimmune'

    # degenerative
    if any(x in text for x in [
        'degenerative', 'parkinson', 'alzheimer'
    ]):
        return 'degenerative'

    return None

In [ ]:
type_emb = model.encode(TYPE_LABELS)

In [ ]:
def predict_type(text):
    emb = model.encode([text])[0]
    sims = np.dot(type_emb, emb)
    return TYPE_LABELS[np.argmax(sims)], np.max(sims)

In [ ]:
def predict_type_final(text):
    text = str(text)

    # rule
    rule = type_rule_boost(text)

    # model
    model_pred, model_conf = predict_type(text)

    # combine
    if rule is None:
        return model_pred

    if model_conf > 0.7:
        return model_pred

    return rule

In [ ]:
from tqdm import tqdm

batch_size = 64
texts = df['input_text'].tolist()

type_preds = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i+batch_size]

    # model
    emb = model.encode(batch)
    sims = np.dot(emb, type_emb.T)

    model_preds = [TYPE_LABELS[np.argmax(s)] for s in sims]
    model_confs = [np.max(s) for s in sims]

    # rules
    rule_preds = [type_rule_boost(t) for t in batch]

    batch_preds = []

    for mp, mc, rp in zip(model_preds, model_confs, rule_preds):

        if rp is None:
            batch_preds.append(mp)

        elif mc > 0.7:
            batch_preds.append(mp)

        else:
            batch_preds.append(rp)

    type_preds.extend(batch_preds)

100%|██████████| 960/960 [03:11<00:00,  5.01it/s]

In [ ]:
df['type_label'] = type_preds

In [ ]:
df[['title','system_label','type_label']].sample(50)

,title,system_label,type_label
24173,A case of Turner's syndrome with Graves' disease and primary hyperparathyroidism,genetic,tumor
34978,COVID-19 in Coincidence with Transient Distal Renal Tubular Acidosis in an Infant,renal,metabolic
37292,Capsule endoscopy: a cause of late small bowel obstruction and perforation,gastrointestinal,infection
3914,Seminal vesicle metastasis after liver transplantation for hepatocellular carcinoma: A case report,respiratory,tumor
10105,Unusual Course of an Aggressive Pituitary Prolactinoma: Case Report and Review of the Literature,neurological,tumor
56144,Chronic active Epstein-Barr virus infection as the basis of neoplasm development. Transformation of chronic lymphocytic leukaemia to NK-cell lymphoma/leukaemia was observed by flow cytometry - a diagnostic report,multisystemic,tumor
26762,Transdermal Spirit (Methanol) Poisoning: A Case Report,dermatological,metabolic
37318,An Unusual Coexistence of Primary Central Nervous System Non-Hodgkin's Lymphoma and Acute Promyelocytic Leukemia,multisystemic,tumor
14023,Pseudohypertriglyceridemia: A Novel Case with Important Clinical Implications,genitourinary,metabolic
47234,Profound Iron Deficiency Anemia and Irreversible Dilated Cardiomyopathy in a Child,cardiovascular,trauma
12751,Unilateral occipital nerve stimulation for bilateral occipital neuralgia: a case report and literature review,neurological,degenerative
13144,Autologous Stem Cell Transplantation in Multiple Myeloma with Renal Failure: Friend or Foe?,renal,autoimmune
36288,The WoundWand and Its Novel Use in Burn Excision Surgery,dermatological,trauma
11202,A Case of Spondyloarthritis in Patient Affected by Unicentric Castleman's Disease Effectively Managed with Surgery Resection and Tocilizumab Treatment,multisystemic,infection
55709,Case Report: a rare primary gastric choriocarcinoma revealed on 18F-FDG PET/CT,hepatobiliary,tumor
27415,"Chorea and tick-borne encephalitis, Poland",neurological,infection
31214,QT Prolongation and Associated Ventricular Tachycardia due to Cardiac Iron Load in a Patient with Thalassemia Major,cardiovascular,metabolic
56177,A case report of QTc prolongation: Drug induced or myocarditis in Severe Acute Respiratory Syndrome Coronavirus 2,cardiovascular,infection
48251,Atherosclerotic Components in Thrombi Retrieved by Thrombectomy for Internal Carotid Artery Occlusion Due to Large Artery Atherosclerosis: A Case Report,hematological,vascular
30952,Spontaneously Expelled Lippes Loop IUD After 40 Years of Use: A Case Report and Review of the Literature,genitourinary,infection
17026,"Case report of squamous cell cancer arising in perineal epidermal inclusion cyst, presenting as rapidly enlarging and cavitating lesion",dermatological,tumor
28479,Difficult Preoperative Diagnosis of Suspected Metal Hypersensitivity in a Case with Early Failure of Bipolar Hemiarthroplasty,dermatological,autoimmune
28544,An Unusual Case of Choledochal Cyst,hepatobiliary,tumor
55807,Management Challenges and Potential Malabsorption of Valproic Acid in a Patient with Bipolar Disorder and Gastrointestinal History,multisystemic,degenerative
1469,Synovial Chondromatosis of Hip in a Young Patient Salvaged With Mini Arthrotomy Without Hip Dislocation - A Case Report,ent,autoimmune
48671,The sagital balance in idiopatic and neuromuscular scoliosis,neurological,degenerative
46096,Delayed Diagnosis of Unilateral Mandibular Condylar Fracture in a Posterior Edentulous Patient,musculoskeletal,trauma
26895,Pediatric stiff-person syndrome with renal failure,neurological,autoimmune
20009,Spontaneous regression of hepatocellular carcinoma: its imaging course leading to complete disappearance,hepatobiliary,tumor
28589,Entomophthoramycosis: A diagnostically challenging presentation of liver space-occupying lesion,hepatobiliary,infection
18836,Chronic abdominal pain after laparoscopic hernia repair due to mesh graft migration to the cecum: a case report,multisystemic,infection
20943,Lipedematous alopecia: clinical and histological analysis of the first male Chinese,dermatological,tumor
60134,Total Femur Replacement as a Salvage Procedure for Failed Distal Femur Megaprosthesis: A Case Report and Literature Reviews,ent,trauma
58292,A Case Report of Whitmore's Disease: A True Masquerader,respiratory,infection
28843,Beta-Blocker and Calcium Channel Blocker Toxicity With BRASH Syndrome: A Case Report,cardiovascular,trauma
23452,Multicystic tuberculosis pericarditis,neurological,infection
41097,Bile Leak following Laparoscopic Cholecystectomy due to Perforated Duodenal Ulcer in Patient with Roux-en-Y Gastric Bypass,gastrointestinal,tumor
30928,EpCAM- and/or NCAM-Expressing Hepatocellular Carcinoma in Which Behavior of Hepatic Progenitor Cell Marker-Positive Cells Are Followed,hepatobiliary,tumor
14207,Adrenal crisis during pregnancy: Case report and obstetric perspective,renal,infection
11463,Paroxysmal Orthostatic Ventricular Tachycardia in a Patient With Supine Hypertension and Orthostatic Hypotension,multisystemic,degenerative
4636,A Rare Cause of Medial Thigh Pain: Does Point-of-Care Ultrasound Scan Have a Role in the Diagnosis of Obturator Hernia in the Emergency Room?,musculoskeletal,infection
49981,Is Gardner-Diamond syndrome related to autoimmunity?,dermatological,autoimmune
24283,Recurrence of Chronic Myeloid Leukemia during Pregnancy Subsequently Achieving Complete Medical Remission,hepatobiliary,tumor
42320,A giant colonic diverticulum presenting as a 'phantom mass': a case report,neurological,tumor
48845,"Case report: Exploring under the tip of the iceberg: A case series of ""self-limiting"" multisystem inflammatory syndrome in children",genetic,infection
36713,A penetrating stab wound of the perianal area causing a combined rectal and bladder injury: one case report,dermatological,trauma
278,Case report: Novel NIPBL-BEND2 fusion gene identified in osteoblastoma-like phosphaturic mesenchymal tumor of the fibula,musculoskeletal,tumor
18026,Retrieval of intrarenal coiled and ruptured guidewire by retrograde intrarenal surgery: A case report and literature review,renal,infection
6431,Rathke's cleft cyst with xanthogranulomatous change: A case report and review of the literature,dermatological,degenerative
40925,Efficacy of Pyrotinib in a Heavily Pretreated Patient with Lung Adenocarcinoma Harboring HER2 Amplification and Exon 20 Insertions: A Case Report,respiratory,tumor

In [ ]:
cols_to_save = [
    'case_id',
    'input_text',
    'system_label',
    'type_label'
]

df[cols_to_save].to_csv("final_labeled_dataset.csv", index=False)

In [ ]:
df_check = pd.read_csv("final_labeled_dataset.csv")
print(df_check.head())
print(df_check.shape)

         case_id  \
0  PMC3738355_01
1  PMC5015624_01
2  PMC6381877_01
3  PMC5287946_01
4  PMC9106225_01

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         input_text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Littoral cell angioma mimicking hepatic tumor [['vascular tumor', 'diagnostic imaging', 'liver', 'pathology', 'spleen']][['vascular tumor', 'diagnostic imaging', 'liver', 'pathology', 'spleen']] Littoral cell angioma is a rare vascular tumor of the spleen that was described by Falk et al. in 1991. Because of the limited number, untypical imaging manifestations, and lack of knowledge on this tumor type, these tumors are often misdiagnosed. In most cases, the tumor presents with multiple small hypoattenuating nodules in the spleen with delayed enhancement. However, solitary littoral cell angiomas have not been well described. We present the CT features of an unusual littoral cell angioma mimicking hepatic tumor.
1                                                                                                                                                                                                                                                                                                                                                                                                                                      Central retinal artery occlusion following laser treatment for ocular ischemic aortic arch syndrome [['mri', 'aortic arch', 'carotid artery stenosis', 'carotid duplex ultrasound', 'ocular ischemic syndrome', 'panretinal laser', 'retrobulbar block']][['mri', 'aortic arch', 'carotid artery stenosis', 'carotid duplex ultrasound', 'ocular ischemic syndrome', 'panretinal laser', 'retrobulbar block']] Objective: Ocular ischemic syndrome is a rare blinding condition generally caused by disease of the carotid artery. We describe a 69-year-old female with a 50 pack-year smoking history with aortic arch syndrome causing bilateral ocular ischemic syndrome. Methods: The patient presented with progressive visual loss and temple pain. Slit lamp biomicroscopy revealed bilateral iris neovascularization. This finding prompted a cardiovascular work up. Panretinal photocoagulation with retrobulbar block was performed in the right eye. Results: A temporal artery biopsy was negative. The carotid duplex ultrasound showed only a 1-39% stenosis. MRA revealed a more proximal occlusion of the aortic branch for which she underwent subclavian carotid bypass surgery. At the one month follow up, the right eye suffered profound vision loss secondary to a central retinal artery occlusion. Conclusion: Ocular neovascularization may be one of the clinical manifestations of aortic arch syndrome. This case also illustrates the limitations of relying solely on carotid duplex ultrasound testing. We caution against overly aggressive panretinal photocoagulation utilizing retrobulbar anesthesia.
2  Promising Combination Therapy with Bevacizumab and Erlotinib in an EGFR-Mutated NSCLC Patient with MET Amplification Who Showed Intrinsic Resistance to Initial EGFR-TKI Therapy [['bevacizumab', 'egfr mutation', 'erlotinib', 'lung cancer', 'met amplification']][['bevacizumab', 'egfr mutation', 'erlotinib', 'lung cancer', 'met amplification']] In lung cancer, several potential mechanisms of intrinsic and acquired resistance to epidermal growth factor receptor (EGFR) tyrosine kinase inhibitors (TKIs) have been explored, including mesenchymal-epithelial transition factor (MET) signaling pathway activation. On the other hand, vascular endothelial growth factor (VEGF) production of EGFR-mutated lung cancer cells is stimulated by predominantly activated MET signaling pathway. Therefore, the inhibition of VEGF axis as the downstream target of MET signaling pathway seems promising. Here, for the first time, we report the potential efficacy of combination therapy with bevacizumab and erlotinib in an EGFR-mutated NSCLC patient with MET amplification who showed intrinsic resistance to initial EGFR-TKI therapy. The patient was a 60-year-old male smoker, showing performance status (PS) 2, who presented with stage IV lung adenocarcinoma (cT4N2M1a) harboring the EGFR exon 19 deletion mutation. He was started on gefitinib at 250 mg/day. However, by 28 days, his symptoms further deteriorated along with the increased tumor size, resulting in PS 3. Then, repeat biopsy was performed, showing the positive MET amplification and the preserved EGFR exon 19 deletion mutation. Therefore, on the basis of the potential efficacy for activated MET signaling pathway as well as the confirmed safety by the known phase II trial for EGFR-mutated patients, the patient was started on combination therapy with bevacizumab at 15 mg/kg every 3 weeks plus erlotinib at 150 mg/day. By 21 days, his symptoms gradually improved along with the decreased tumor size, resulting in better PS with no severe toxicities.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Malignant adenohypophysis spindle cell oncocytoma with repeating recurrences and a high Ki-67 index nannan Adenohypophysis spindle cell oncocytoma (ASCO) is a rare tumor recently reported by Roncaroli et al in 2002. This tumor is considered a grade I tumor by the World Health Organization.We report a rare case of malignant ASCO with repeating recurrences and a high Ki-67 index-a challenging diagnosis guided by clinical presentations, radiological signs, and postoperative pathological tests.We represent a 30-year-old man who had suffered from headaches, diplopia, and impaired visual field and acuity. His magnetic resonance imaging revealed an abnormal sellar mass and was originally misdiagnosed as a pituitary macroadenoma. We present detailed analysis of the patient's disease course and review relevant literature.When surgically treated, the specimen revealed a typical histopathology pattern of ASCO. The tumor recurred for several times and the patient underwent 3 surgeries and 1 γ-knife treatment, which was accompanied by a continuously increasing Ki-67 index.This is the first reported case of malignant ASCO (WHO III-IV grade). Despite its rarity, ASCO should be considered in the differential diagnosis of sellar lesions that mimic pituitary adenomas.
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            A novel mucocele: Myxoglobulosis [['mucocele', 'mucus extravasation cyst', 'myxoglobulosis']][['mucocele', 'mucus extravasation cyst', 'myxoglobulosis']] Oral extravasation mucoceles are among the most widely recognized submucosal lesions which are usually a result of trauma involving salivary glands and their ducts. This paper reports a case of a 40-year-old female patient with a chief complaint of a painless swelling on the lower lip since 6 months. Upon a provisional diagnosis of mucocele, surgical excision was carried out. Histopathological examination revealed a mucus extravasation cyst having lumen filled with unique mucinous globular structures similar to a rare variant of appendiceal mucocele, myxoglobulosis.

     system_label type_label
0   hepatobiliary      tumor
1  cardiovascular   vascular
2     respiratory      tumor
3   multisystemic      tumor
4             ent     trauma
(61437, 4)

In [ ]:
pip install transformers datasets scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
import pandas as pd

df = pd.read_csv("final_labeled_dataset.csv")

df = df.dropna()
df = df.reset_index(drop=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_system = LabelEncoder()
df['system_id'] = le_system.fit_transform(df['system_label'])

In [ ]:
le_type = LabelEncoder()
df['type_id'] = le_type.fit_transform(df['type_label'])

In [ ]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
def tokenize(batch):
    return tokenizer(
        batch['input_text'],
        padding='max_length',
        truncation=True,
        max_length=512
    )

In [ ]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)

Map:   0%|          | 0/55293 [00:00<?, ? examples/s]

Map:   0%|          | 0/6144 [00:00<?, ? examples/s]

In [ ]:
import pandas as pd

df = pd.read_csv("/content/final_labeled_dataset.csv")

df = df.dropna()
df = df.reset_index(drop=True)

print(df.shape)
print(df.head())

(61437, 4)
         case_id                                         input_text  \
0  PMC3738355_01  Littoral cell angioma mimicking hepatic tumor ...
1  PMC5015624_01  Central retinal artery occlusion following las...
2  PMC6381877_01  Promising Combination Therapy with Bevacizumab...
3  PMC5287946_01  Malignant adenohypophysis spindle cell oncocyt...
4  PMC9106225_01  A novel mucocele: Myxoglobulosis [['mucocele',...

     system_label type_label
0   hepatobiliary      tumor
1  cardiovascular   vascular
2     respiratory      tumor
3   multisystemic      tumor
4             ent     trauma

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_system = LabelEncoder()
le_type = LabelEncoder()

df['system_id'] = le_system.fit_transform(df['system_label'])
df['type_id'] = le_type.fit_transform(df['type_label'])

In [ ]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df, test_size=0.1, random_state=42, stratify=df['system_id']
)

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
import torch
from torch.utils.data import Dataset

class MedicalDataset(Dataset):
    def __init__(self, df, tokenizer):
        self.texts = df['input_text'].tolist()
        self.system = df['system_id'].tolist()
        self.type = df['type_id'].tolist()
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            padding='max_length',
            truncation=True,
            max_length=512,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'system_label': torch.tensor(self.system[idx]),
            'type_label': torch.tensor(self.type[idx])
        }

In [ ]:
from torch.utils.data import DataLoader

train_dataset = MedicalDataset(train_df, tokenizer)
val_dataset = MedicalDataset(val_df, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8)

In [ ]:
from transformers import AutoModel
import torch.nn as nn

class MultiTaskModel(nn.Module):
    def __init__(self, num_system, num_type):
        super().__init__()

        self.encoder = AutoModel.from_pretrained("distilbert-base-uncased")
        hidden = self.encoder.config.hidden_size

        self.dropout = nn.Dropout(0.3)

        self.system_head = nn.Linear(hidden, num_system)
        self.type_head = nn.Linear(hidden, num_type)

    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)

        cls = outputs.last_hidden_state[:, 0]
        cls = self.dropout(cls)

        system_logits = self.system_head(cls)
        type_logits = self.type_head(cls)

        return system_logits, type_logits

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = MultiTaskModel(
    num_system=len(le_system.classes_),
    num_type=len(le_type.classes_)
).to(device)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)

loss_fn = nn.CrossEntropyLoss()

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
from tqdm import tqdm

epochs = 3

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader):
        optimizer.zero_grad()

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        sys_labels = batch['system_label'].to(device)
        type_labels = batch['type_label'].to(device)

        sys_logits, type_logits = model(input_ids, attention_mask)

        loss_sys = loss_fn(sys_logits, sys_labels)
        loss_type = loss_fn(type_logits, type_labels)

        loss = loss_sys + loss_type

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss}")

100%|██████████| 6912/6912 [47:27<00:00,  2.43it/s]

Epoch 1, Loss: 7788.245893858373

100%|██████████| 6912/6912 [47:20<00:00,  2.43it/s]

Epoch 2, Loss: 3976.780069018714

100%|██████████| 6912/6912 [47:20<00:00,  2.43it/s]

Epoch 3, Loss: 2619.1351494453847

In [ ]:
from sklearn.metrics import f1_score

model.eval()

sys_preds, sys_true = [], []
type_preds, type_true = [], []

with torch.no_grad():
    for batch in val_loader:

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)

        sys_logits, type_logits = model(input_ids, attention_mask)

        sys_pred = torch.argmax(sys_logits, dim=1).cpu().numpy()
        type_pred = torch.argmax(type_logits, dim=1).cpu().numpy()

        sys_preds.extend(sys_pred)
        type_preds.extend(type_pred)

        sys_true.extend(batch['system_label'].numpy())
        type_true.extend(batch['type_label'].numpy())

In [ ]:
print("System F1:", f1_score(sys_true, sys_preds, average='weighted'))
print("Type F1:", f1_score(type_true, type_preds, average='weighted'))

System F1: 0.9402400268246227
Type F1: 0.889337434415402

In [ ]:
torch.save(model.state_dict(), "medical_model.pt")